language: node_js
node_js:
  - "6"

install:
  - npm install

script:
  - ./node_modules/eslint/bin/eslint.js --ext .js,.vue src
  - npm run unit

after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info
